# Generated by Django 4.2 on 2023-04-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('surname', models.CharField(max_length=200)),
                ('fatherName', models.CharField(max_length=200)),
                ('viloyat', models.CharField(max_length=200)),
                ('tuman', models.CharField(max_length=200)),
                ('mahalla', models.CharField(max_length=200)),
                ('polikilinika', models.IntegerField()),
                ('uy', models.IntegerField()),
                ('tel', models.CharField(max_length=9)),
                ('born_at', models.DateField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
